In [3]:
import numpy as np
import pandas as pd
import json
import os

In [4]:
# DATA Path
DATAPATH_JSON = './json'

- Product info stored in product_rows and transfered into pandas table
- Product overview is stored in a dict

In [31]:
product_rows = []
product_overview = {}
for filename in os.listdir(DATAPATH_JSON):
    with open(f'{DATAPATH_JSON}/{filename}', 'r') as f:
        product = json.load(f)
        id_, overview = product['id'], product['overview']
        product_overview[id_] = overview
        # remove overview from the product dict
        product.pop('overview')
        # title is the same as id
        product.pop('title')
        # store product in a pandas dataframe
        product_rows.append(product)

In [32]:
df_1 = pd.DataFrame(product_rows)
df_1

,id,price,discount,country,quantity,missOverview,missDiscount,missCountry,missQuantity,missPrice
0,B071FXZBMV,8.99,0.00,US,30,False,True,False,False,False
1,B096WLN8XJ,44.00,0.00,US,2,True,True,False,False,False
2,B09B2QR6LR,17.90,0.00,US,7,True,True,False,False,False
3,B09T3P7MJ9,16.25,0.00,US,13,False,True,False,False,False
4,B003I7HS5M,0.00,0.00,US,0,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
781,B09CG6P9YZ,118.14,211.85,US,30,False,False,False,False,False
782,B002PXW15C,0.00,0.00,US,0,True,True,False,False,True
783,B00KVHEAXK,14.99,0.00,US,30,True,True,False,False,False
784,B004XFUSRI,4.94,0.00,US,36,False,True,False,False,False
785,B08GLXJTSP,6.99,6.00,US,100,False,False,False,False,False

In [34]:
product_overview['B071FXZBMV']

{'_Color_': 'Black',
 '_Brand_': 'OHill',
 '_Item_Weight_': '0.15 Pounds',
 '_Binding_': 'Unknown Binding'}